"""
Tool: save_artifact -- allows agents to save files to their artifacts directory.

Artifacts are files produced by agents during their work -- reports, analysis,
generated images, PDFs, markdown output, etc. They are stored under
shared/agents/<agent-id>/artifacts/ and are accessible via the web UI.

Two usage modes:
  - source_path: stream an existing file on disk (binaries, images, PDFs)
    via the execution backend's cat_file_bytes, which works across sandbox
    (Docker exec + tmpfs), SSH remote, tunnel RPC, and local filesystem.
  - content: write text content (UTF-8) generated by the agent.
"""

import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def _artifacts_dir(agent_id: str) -> str:
    d = os.path.join(BASE_DIR, 'shared', 'agents', agent_id, 'artifacts')
    os.makedirs(d, exist_ok=True)
    return d


def execute(agent: dict, args: dict) -> dict:
    agent_id = agent.get('id', agent.get('agent_id', ''))
    if not agent_id:
        return {'error': 'Agent ID not found in context'}

    filename = args.get('filename', '').strip()
    content = args.get('content', '')
    mime_type = args.get('mime_type', '')
    source_path = args.get('source_path', '').strip()

    if not filename:
        return {'error': 'filename is required'}

    # Security: prevent path traversal
    if '/' in filename or '\\' in filename or '..' in filename:
        return {'error': 'Invalid filename'}

    artifacts_dir = _artifacts_dir(agent_id)
    filepath = os.path.join(artifacts_dir, filename)

    try:
        if source_path:
            # --- source_path mode: stream file bytes into artifacts ---
            workplace_id = agent.get('workplace_id')
            sandbox_enabled = agent.get('sandbox_enabled', False)

            if workplace_id:
                from backend.workplaces.manager import workplace_manager

                try:
                    backend = workplace_manager.get_backend(
                        workplace_id, sandbox_enabled=sandbox_enabled
                    )
                except RuntimeError as e:
                    return {'error': f'Workplace error: {str(e)}'}
            elif sandbox_enabled:
                # Sandbox with no workplace: resolve path through execution backend
                from backend.tools.lib.exec_backend import registry as exec_registry
                session_id = agent.get('session_id', 'default')
                backend = exec_registry.get_backend(session_id, agent)
            else:
                # No workplace, no sandbox: use local backend
                from backend.tools.lib.backends.local_backend import LocalBackend
                backend = LocalBackend(session_id=agent.get('session_id', 'default'))

            # Resolve path when the backend has path translation (Docker mount)
            resolved = backend.resolve_path(source_path) if hasattr(backend, 'resolve_path') else source_path

            result = backend.cat_file_bytes(resolved)
            if 'error' in result:
                return {'error': f'Failed to read source file: {result["error"]}'}

            with open(filepath, 'wb') as f:
                f.write(result['bytes'])

        else:
            # --- content mode: write text (UTF-8) ---
            if not content:
                return {'error': 'Either content or source_path must be provided'}
            # Normalise smart quotes in text mode artifacts
            from backend.normalizer import normalize_code_quotes
            content = normalize_code_quotes(content)
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(content)

        stat = os.stat(filepath)
        return {
            'result': 'Artifact saved successfully',
            'filepath': filepath,
            'filename': filename,
            'size': stat.st_size,
        }
    except Exception as e:
        return {'error': f'Failed to save artifact: {str(e)}'}
